Add function to get datetime from week number
KadaDev/week_of_year pull request #1
Opened 2021-01-08 21:44 UTC by Maistho

Adds a new function to create a DateTime from year+week number and optional weekday

2021-06-24 18:13 UTC, marko requested changes
Fix ToDo or explicitly support and document under/overflow

2023-07-28 12:05 UTC, Maistho commented
> Fix ToDo or explicitly support and document under/overflow

Removed TODO and added small amount of additional documentation on overflow/underflow

2023-07-30 11:03 UTC, marko approved these changes

2023-07-30 12:51 UTC, merged

2023-07-30 13:00 UTC, Maistho commented
Released as v2.2.0